# configuration for authguardian-graylog setup
name: graylog

# services definition for the authguardian-graylog application
services:
  # mongodb services - used for storing graylog configuration
  mongo-graylog:
    image: mongo:6.0.5-jammy
    container_name: mongodb
    volumes:
      - /DATA/AppData/$AppID/db:/data/db
    restart: unless-stopped

    # casaos specific configuration for mongodb
    x-casaos:
      volumes:
        - container: /data/db
          description:
            en_us: "Container Path: /data/db"

# CasaOS specific configuration
x-casaos:
  architectures:
    - amd64
    - arm64
  main: graylog
  description:
    en_us: |
      Graylog provides answers to your team’s security, application, and IT infrastructure questions by enabling you to combine, enrich, correlate, query, and visualize all your log data in one place.
  tagline: 
    en_us: Graylog is a complete observability stack that allows you to monitor and analyze metrics, logs and traces. It allows you to query, visualize, alert on and understand your data.
  developer: ""
  author: authguardian
  icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/graylog.png
  thumbnail: ""
  title:
    en_us: Graylog
  category: Security
  port_map: ""