# configuration for authguardian-graylog setup
name: graylog

# services definition for the authguardian-graylog application
services:
  # Graylog UI services
  graylog:
    image: graylog/graylog:5.1
    container_name: graylog
    environment:
      # CHANGE ME (must be at least 16 characters)!
      GRAYLOG_PASSWORD_SECRET: "somepasswordpepper"
      # Password: admin
      GRAYLOG_ROOT_PASSWORD_SHA2: "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918"
      GRAYLOG_HTTP_BIND_ADDRESS: "0.0.0.0:9000"
      GRAYLOG_HTTP_EXTERNAL_URI: "http://localhost:9000/"
      GRAYLOG_ELASTICSEARCH_HOSTS: "http://opensearch:9200"
      GRAYLOG_MONGODB_URI: "mongodb://mongodb:27017/graylog"
      GRAYLOG_TIMEZONE: "America/Kentucky/Louisville"
      TZ: "America/Kentucky/Louisville"
    entrypoint: /usr/bin/tini -- wait-for-it opensearch:9200 -- /docker-entrypoint.sh
    volumes:
      - /DATA/AppData/$AppID/config/graylog/graylog.conf:/usr/share/graylog/config/graylog.conf
      - /DATA/AppData/$AppID/graylog_data:/usr/share/graylog/data
    restart: always
    depends_on:
      opensearch:
        condition: "service_started"
      mongo:
        condition: "service_started"
    ports:
      - 9000:9000/tcp   # Graylog web interface and REST API
      - 1514:1514/tcp   # Syslog
      - 1514:1514/udp   # Syslog
      - 12201:12201/tcp # GELF
      - 12201:12201/udp # GELF
  
    x-casaos:
      volumes:
        - container: /usr/share/graylog/config/graylog.conf
          description:
            en_us: "Graylog config"
        - container: /usr/share/graylog/data
          description:
            en_us: "Graylog data"

  # mongodb services - used for storing graylog configuration
  mongodb:
    image: mongo:6.0.5-jammy
    volumes:
      - /DATA/AppData/$AppID/db:/data/db
    restart: unless-stopped

    # casaos specific configuration for mongodb
    x-casaos:
      volumes:
        - container: /data/db
          description:
            en_us: "Container Path: /data/db"
  
  opensearch:
    image: opensearchproject/opensearch:2
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - "bootstrap.memory_lock=true"
      - "discovery.type=single-node"
      - "action.auto_create_index=false"
      - "plugins.security.ssl.http.enabled=false"
      - "plugins.security.disabled=true"
    volumes:
      - /DATA/AppData/$AppID/log_data:/usr/share/opensearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 9200:9200/tcp
    restart: unless-stopped
    depends_on:
      - mongodb

    x-casaos: # CasaOS specific configuration
      volumes:
        - container: usr/share/opensearch/data
          description:
            en_us: "Container Path: /usr/share/opensearch/data"
      ports:
        - container: "9200"
          description:
            en_us: "Container Port: 9200"
# CasaOS specific configuration
x-casaos:
  architectures:
    - amd64
    - arm64
  main: graylog
  description:
    en_us: |
      Graylog provides answers to your team’s security, application, and IT infrastructure questions by enabling you to combine, enrich, correlate, query, and visualize all your log data in one place.
  tagline: 
    en_us: Graylog is a complete observability stack that allows you to monitor and analyze metrics, logs and traces. It allows you to query, visualize, alert on and understand your data.
  developer: "Graylog"
  author: authguardian
  icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/graylog.png
  screenshot_link:
    - https://raw.githubusercontent.com/authguardian/casaos-authguardian/main/Apps/Graylog/graylog-1.png
    - https://raw.githubusercontent.com/authguardian/casaos-authguardian/main/Apps/Graylog/graylog-2.png
    - https://raw.githubusercontent.com/authguardian/casaos-authguardian/main/Apps/Graylog/graylog-3.png
    - https://raw.githubusercontent.com/authguardian/casaos-authguardian/main/Apps/Graylog/graylog-4.png
  thumbnail: ""
  title:
    en_us: Graylog
  category: Network Security
  port_map: "9000"