# configuration for authguardian-graylog setup
name: graylog

networks:
  graynet:
    driver: bridge

# services definition for the authguardian-graylog application
services:
  # mongodb services - used for storing graylog configuration
  mongo-graylog:
    image: mongo:6.0.5-jammy
    container_name: mongodb
    # ports:
    #   - 27017:27017
    networks:
      - graynet
    volumes:
      - /DATA/AppData/$AppID/db:/data/db
    restart: unless-stopped

    # casaos specific configuration for mongodb
    x-casaos:
      volumes:
        - container: /data/db
          description:
            en_us: "Container Path: /data/db"
      # ports:
      #   - container: "27017"
      #     description:
      #       en_us: "Container Port: 27017"


# CasaOS specific configuration
x-casaos:
  architectures:
    - amd64
    - arm64
  main: graylog
  description:
    en_us: Self-hosted Graylog instance
  tagline: 
    en_us: Graylog
  developer: ""
  author: authguardian
  icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/graylog.png
  thumbnail: ""
  title:
    en_us: Graylog
  category: AuthGuardianCasaOS
  port_map: ""